resources:
  jobs:
    update-and-evaluate-traces:
      name: arxiv-update-and-evaluate-traces
      schedule:
        quartz_cron_expression: "0 0 7 * * ?"
        timezone_id: "Europe/Amsterdam"
        pause_status: "${var.schedule_pause_status}"
      budget_policy_id: "${var.usage_policy_id}"
      environments:
        - environment_key: default
          spec:
            environment_version: "4"
            dependencies:
              - ../dist/*.whl

      tasks:
        - task_key: update_and_evaluate
          environment_key: default
          notebook_task:
            notebook_path: deployment_notebooks/production_monitoring.py
            base_parameters:
              env: "${bundle.target}"
