resources:
  jobs:
    house-price:
      name: hotel-booking-workflow
      schedule:
        quartz_cron_expression: "0 0 6 ? * MON"
        timezone_id: "Europe/Amsterdam"
        pause_status: ${var.schedule_pause_status}
      tags:
        project_name: "hotel-booking"
      job_clusters:
        - job_cluster_key: "hotel-booking-cluster"
          new_cluster:
            spark_version: "15.4.x-scala2.12"
            data_security_mode: "SINGLE_USER"
            node_type_id: "r3.xlarge"
            driver_node_type_id: "r3.xlarge"
            autoscale:
              min_workers: 1
              max_workers: 1

      tasks:
        - task_key: "preprocessing"
          job_cluster_key: "hotel-booking-cluster"
          spark_python_task:
            python_file: "scripts/01.process_data.py"
            parameters:
              - "--root_path"
              - ${workspace.root_path}
              - "--env"
              - ${bundle.target}
          libraries:
           - whl: ./dist/*.whl
        - task_key: "train_model"
          job_cluster_key: "hotel-booking-cluster"
          depends_on:
            - task_key: "preprocessing"
          spark_python_task:
            python_file: "scripts/02.train_register_fe_model.py"
            parameters:
              - "--root_path"
              - ${workspace.root_path}
              - "--env"
              - ${bundle.target}
              - "--git_sha"
              - ${var.git_sha}
              - "--job_run_id"
              - "{{job.id}}"
              - "--branch"
              - ${var.branch}
          libraries:
            - whl: ./dist/*.whl
        - task_key: model_updated
          condition_task:
            op: "EQUAL_TO"
            left: "{{tasks.train_model.values.model_updated}}"
            right: "1"
          depends_on:
            - task_key: "train_model"
        - task_key: "deploy_model"
          depends_on:
            - task_key: "model_updated"
              outcome: "true"
          job_cluster_key: "hotel-booking-cluster"
          spark_python_task:
            python_file: "scripts/03.deploy_model.py"
            parameters:
              - "--root_path"
              - ${workspace.root_path}
              - "--env"
              - ${bundle.target}
          libraries:
            - whl: ./dist/*.whl