name: MLOPs with Databricks

on:
  push:
    branches:
      - 'main'

env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  deploy_to_acc_and_prd:
    name: Set Up Environment
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [acc, prd]

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install Databricks CLI
        uses: databricks/setup-cli@49580195afe1ccb06d195764a1d0ae9fabfe2edd #v0.246.0
        with:
          version: 0.246.0

      - name: Install uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 #v5.4.1

      - name: Install the dependencies
        run: |
          uv sync --all-extras

      - name: Deploy to Databricks
        env:
          DATABRICKS_BUNDLE_ENV: ${{ matrix.environment }}
        run: |
            if [ "${{ matrix.environment }}" = "prd" ]; then
            echo "VERSION=$(cat version.txt)" > version.txt
            git tag $VERSION
            git push origin $VERSION
            fi
            databricks bundle deploy --var="git_sha=${{ github.sha }}"
            
